language: c
sudo: required

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

before_install:
  - export PATH=~/.cabal/bin:/opt/cabal/$CABAL_VER/bin:/opt/ghc/$GHC_VER/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

matrix:
  include:
    - env: CABAL_VER=1.22 GHC_VER=7.10.3
      addons:
        apt:
          packages:
            - cabal-install-1.22
            - ghc-7.10.3
            - zlib1g-dev
            - libncurses5-dev
          sources:
            - hvr-ghc

install:
  - cabal update
  - git clone https://github.com/cedille/cedille.git
  - cd cedille
  - make agda-install
  - make
  

